Numero1 = int(input("Ingrese el primer Numero: "))
Numero2 = int(input("Ingrese el segundo Numero: "))
Numero3 = int(input("Ingrese el tercer numero Numero: "))
suma = (Numero1+Numero2+Numero3)
print(f"{Numero1}+{Numero2}+{Numero3}={suma}")